import express from 'express';
import cors from 'cors';
import dotenv from 'dotenv';
dotenv.config();
const app = express();
app.use(cors());
app.use(express.json());
app.get('/health', (req, res) => res.json({ ok: true, app: 'whatnot-lite' }));
app.get('/', (req, res) => res.send('whatnot-lite API running. See README for roadmap.'));
const port = process.env.PORT || 3000;
app.listen(port, () => console.log(`whatnot-lite on ${port}`));
